Traceback (most recent call last):
  File "main.py", line 776, in <module>
  File "main.py", line 770, in main
  File "main.py", line 266, in __init__
IOError: unable to read font file 'data/fonts/Laconic_Bold.otf'
